<a href="https://colab.research.google.com/github/sielefaith/Neural-Nets/blob/feature/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.environ["KAGGLE_CONFIG_DIR"] = '/'

In [ ]:
!kaggle datasets download -d zalando-research/fashionmnist

 79% 54.0M/68.8M [00:00<00:00, 47.8MB/s]
100% 68.8M/68.8M [00:00<00:00, 101MB/s] 


In [ ]:
!unzip \*.zip && rm *.zip

Archive:  fashionmnist.zip
  inflating: fashion-mnist_test.csv  
  inflating: fashion-mnist_train.csv  
  inflating: t10k-images-idx3-ubyte  
  inflating: t10k-labels-idx1-ubyte  
  inflating: train-images-idx3-ubyte  
  inflating: train-labels-idx1-ubyte  


In [19]:
import pandas as pd
import numpy as np


df = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/fashion-mnist_train.csv",header=0)
#df.head()

df['label'].values.reshape(1,60000)

#df.drop('label', axis=1)

#train = np.array(df / 255.0)

array([[2, 9, 6, ..., 8, 8, 7]])

In [27]:
import numpy as np

#create a new array with the right dimensions
labels = df['label'].values.reshape(1,60000)
#fill it with zeros
labels_ = np.zeros((60000,10))
#print(labels_)
# set to 1 only the columns related to the label itself
labels_[np.arange (60000), labels] = 1
#print(labels_)
# transpose it, to have the dimensions we want at the end: (10, 60000),
labels_ = labels_.transpose()
#print(labels_)
#converts the pandas data frame into a NumPy array)
labels_ = np.array(labels_)
print(labels_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
